services:
  - type: web
    name: jdr-character-sheet
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: AUTH_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
